// Seed Stripe with the 4 paid CryptoGuide products and their monthly/yearly
// prices, then write the 8 price IDs into .env.
//
// Usage: put your Stripe TEST secret key in .env.local as STRIPE_SECRET_KEY,
// then run `npm run stripe:seed`.
//
// Idempotent: prices carry a stable lookup_key, so re-running reuses existing
// products/prices instead of creating duplicates.
import fs from 'node:fs'
import Stripe from 'stripe'

// --- minimal .env loader (real process env always wins) ------------------
function loadEnv(file) {
  if (!fs.existsSync(file)) return
  for (const line of fs.readFileSync(file, 'utf8').split(/\r?\n/)) {
    const m = line.match(/^\s*([\w.-]+)\s*=\s*(.*)\s*$/)
    if (!m) continue
    const key = m[1]
    let val = m[2]
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1)
    }
    if (!(key in process.env)) process.env[key] = val
  }
}
loadEnv('.env.local')
loadEnv('.env')

const secret = process.env.STRIPE_SECRET_KEY
if (!secret) {
  console.error('✗ STRIPE_SECRET_KEY is not set. Put your Stripe TEST key in .env.local.')
  process.exit(1)
}
if (!secret.startsWith('sk_test_')) {
  console.warn('⚠ STRIPE_SECRET_KEY is not a test key (sk_test_...). Proceeding anyway.')
}

const stripe = new Stripe(secret)

const PLANS = [
  { key: 'starter', name: 'Starter', monthly: 59, yearly: 590 },
  { key: 'trader', name: 'Trader', monthly: 149, yearly: 1490 },
  { key: 'pro', name: 'Pro', monthly: 499, yearly: 4990 },
  { key: 'whale', name: 'Whale', monthly: 1499, yearly: 14990 },
]
const INTERVALS = [
  { id: 'monthly', stripe: 'month' },
  { id: 'yearly', stripe: 'year' },
]

const envUpdates = {}

for (const plan of PLANS) {
  const lookupKeys = INTERVALS.map((i) => `cg_${plan.key}_${i.id}`)

  const existing = await stripe.prices.list({
    lookup_keys: lookupKeys,
    active: true,
    expand: ['data.product'],
    limit: 10,
  })

  // Resolve the product: from an existing price, else search by metadata,
  // else create it.
  let product =
    existing.data[0]?.product && typeof existing.data[0].product === 'object'
      ? existing.data[0].product
      : null

  if (!product) {
    const found = await stripe.products
      .search({ query: `metadata['plan']:'${plan.key}' AND active:'true'` })
      .catch(() => ({ data: [] }))
    product = found.data[0] ?? null
  }

  if (!product) {
    product = await stripe.products.create({
      name: `CryptoGuide ${plan.name}`,
      description: `CryptoGuide ${plan.name} subscription`,
      metadata: { plan: plan.key },
    })
    console.log(`+ product ${plan.name} (${product.id})`)
  } else {
    console.log(`= product ${plan.name} (${product.id})`)
  }

  for (const interval of INTERVALS) {
    const lookupKey = `cg_${plan.key}_${interval.id}`
    let price = existing.data.find((p) => p.lookup_key === lookupKey)
    const amount = plan[interval.id]

    if (!price) {
      price = await stripe.prices.create({
        product: product.id,
        currency: 'usd',
        unit_amount: amount * 100,
        recurring: { interval: interval.stripe },
        lookup_key: lookupKey,
        metadata: { plan: plan.key, interval: interval.id },
      })
      console.log(`  + ${interval.id} $${amount} (${price.id})`)
    } else {
      console.log(`  = ${interval.id} $${amount} (${price.id})`)
    }

    const envName = `STRIPE_PRICE_${plan.key.toUpperCase()}_${interval.id.toUpperCase()}`
    envUpdates[envName] = price.id
  }
}

// --- write the 8 price IDs into .env (replace in place, else append) -----
function writeEnv(file, updates) {
  let lines = fs.existsSync(file) ? fs.readFileSync(file, 'utf8').split(/\r?\n/) : []
  const seen = new Set()
  lines = lines.map((line) => {
    const m = line.match(/^\s*([\w.-]+)\s*=/)
    if (m && updates[m[1]] !== undefined) {
      seen.add(m[1])
      return `${m[1]}=${updates[m[1]]}`
    }
    return line
  })
  const toAppend = Object.entries(updates).filter(([k]) => !seen.has(k))
  if (toAppend.length) {
    if (lines.length && lines[lines.length - 1].trim() !== '') lines.push('')
    lines.push('# Stripe price IDs — generated by scripts/seed-stripe.mjs')
    for (const [k, v] of toAppend) lines.push(`${k}=${v}`)
    lines.push('')
  }
  fs.writeFileSync(file, lines.join('\n'))
}

writeEnv('.env', envUpdates)

console.log('\n✓ Seeded 4 products × 2 prices. Wrote 8 price IDs to .env:')
for (const [k, v] of Object.entries(envUpdates)) console.log(`  ${k}=${v}`)
