import { clerkMiddleware, createRouteMatcher } from '@clerk/nextjs/server'
import createIntlMiddleware from 'next-intl/middleware'
import { NextRequest, NextResponse, type NextFetchEvent, type NextMiddleware } from 'next/server'

import { routing, type Locale } from './i18n/routing'

const intlMiddleware = createIntlMiddleware(routing)

// Routes that require a signed-in user.
const isProtectedRoute = createRouteMatcher([
  '/:locale/profile(.*)',
  '/profile(.*)',
  '/:locale/billing(.*)',
  '/billing(.*)',
  '/:locale/dashboard(.*)',
  '/dashboard(.*)',
  // Crypto Map is PUBLIC (it is the home page's main view) — read-only map
  // APIs are IP rate-limited instead of login-gated.
])

// First-visit language policy (no cookie, no locale in the URL): ALWAYS
// English. The site is global-first; Korean is one click away via the locale
// switcher, and that explicit choice (NEXT_LOCALE cookie) is remembered and
// always wins. Browser language / geo are deliberately NOT used — next-intl's
// Accept-Language negotiation is bypassed by forcing the header to 'en'.
const FIRST_VISIT_LOCALE: Locale = 'en'

// Top-level page segments that exist under /[locale]. Anything else is a
// 404 — but because [locale]/loading.tsx streams the shell first, a
// notFound() thrown by the catch-all page arrives after the 200 status has
// been sent (soft 404). Middleware knows the answer before rendering, so it
// rewrites unknown paths with a real 404 status (the localized not-found
// page still renders).
const KNOWN_SEGMENTS = new Set([
  'admin', 'alerts', 'api-center', 'billing', 'brief', 'dashboard', 'data', 'education',
  'enterprise', 'insights', 'legal', 'map', 'news', 'onchain', 'patterns', 'portfolio',
  'profile', 'referral', 'reports', 'sign-in', 'sign-up',
  // Metadata file route generated by Next under the locale segment
  // (src/app/[locale]/opengraph-image.tsx). Add twitter-image/icon here only
  // if such files are created — otherwise they must 404 like any other path.
  'opengraph-image',
])
function isUnknownPage(pathname: string): boolean {
  const locale = pathnameLocale(pathname)
  if (!locale) return false
  const rest = pathname.slice(locale.length + 1).replace(/^\/+/, '')
  if (!rest) return false
  return !KNOWN_SEGMENTS.has(rest.split('/')[0])
}

function pathnameLocale(pathname: string): Locale | undefined {
  return routing.locales.find(
    (locale) => pathname === `/${locale}` || pathname.startsWith(`/${locale}/`),
  )
}

// Cookie-authenticated, browser-initiated mutation routes that must be
// CSRF-protected by a same-origin check. Excludes signature-verified
// webhooks (/api/billing/webhook, /api/webhooks/*), API-key routes
// (/api/v1/*) and cron-secret routes (they carry no browser Origin).
const CSRF_MUTATING_METHODS = new Set(['POST', 'PUT', 'PATCH', 'DELETE'])
function isCsrfProtected(pathname: string): boolean {
  if (pathname === '/api/billing/webhook' || pathname.startsWith('/api/webhooks/')) return false
  return (
    pathname.startsWith('/api/me/') ||
    pathname.startsWith('/api/admin/') ||
    pathname === '/api/consent' ||
    pathname === '/api/events' ||
    pathname === '/api/billing/checkout' ||
    pathname === '/api/billing/cancel' ||
    pathname === '/api/billing/change' ||
    pathname === '/api/billing/refund' ||
    // Pipeline triggers: cron (x-cron-secret, exempt below) or a signed-in
    // admin — the admin path is cookie-auth, so same-origin applies.
    pathname === '/api/news/ingest' ||
    pathname === '/api/news/summarize' ||
    pathname === '/api/brief/generate' ||
    pathname === '/api/brief/announce' ||
    pathname === '/api/reports/generate' ||
    pathname === '/api/alerts/run' ||
    pathname === '/api/referral/qualify' ||
    pathname === '/api/map/sync'
  )
}

function sameOriginOk(request: NextRequest): boolean {
  const origin = request.headers.get('origin')
  if (!origin) return false
  let parsed: URL
  try {
    parsed = new URL(origin)
  } catch {
    return false
  }
  const host = request.headers.get('x-forwarded-host') ?? request.headers.get('host')
  if (!host) return false
  // Compare scheme + host, not host alone: http://host must not satisfy a
  // check for https://host.
  const proto =
    request.headers.get('x-forwarded-proto')?.split(',')[0].trim() ||
    request.nextUrl.protocol.replace(':', '')
  return parsed.origin === `${proto}://${host}`
}

// Clerk's session cookie is a JWT (header.payload.signature). A cookie with
// three segments whose header/payload are not base64url JSON makes
// clerkMiddleware throw (500 on every page until the cookie expires). Treat
// such a cookie as absent and clear it on the way out.
const SESSION_COOKIE = '__session'
function base64UrlJsonOk(part: string): boolean {
  try {
    const b64 = part.replace(/-/g, '+').replace(/_/g, '/')
    const padded = b64 + '='.repeat((4 - (b64.length % 4)) % 4)
    JSON.parse(atob(padded))
    return true
  } catch {
    return false
  }
}
function sessionCookieMalformed(value: string | undefined): boolean {
  if (!value) return false
  const parts = value.split('.')
  if (parts.length !== 3) return true
  return !(base64UrlJsonOk(parts[0]) && base64UrlJsonOk(parts[1]))
}
function withoutSessionCookie(request: NextRequest): NextRequest {
  const headers = new Headers(request.headers)
  const cookie = (request.headers.get('cookie') ?? '')
    .split(';')
    .map((c) => c.trim())
    .filter((c) => c && !c.startsWith(`${SESSION_COOKIE}=`))
    .join('; ')
  if (cookie) headers.set('cookie', cookie)
  else headers.delete('cookie')
  // NextRequest(input: Request) copies only the URL — pass method/body
  // explicitly so API mutations keep their semantics (CSRF check, handler).
  return new NextRequest(request.url, {
    method: request.method,
    headers,
    body: request.body,
    // Required by undici/edge for stream bodies; not in RequestInit typings.
    ...({ duplex: 'half' } as Record<string, unknown>),
  })
}

// Internal Clerk diagnostics (x-clerk-auth-status/-reason/-message) must not
// reach browsers.
const CLERK_DEBUG_HEADERS = ['x-clerk-auth-status', 'x-clerk-auth-reason', 'x-clerk-auth-message']

const clerkHandler = clerkMiddleware(async (auth, request) => {
  const { pathname } = request.nextUrl

  // API routes only need Clerk's auth context, not locale routing.
  // /r/* are referral landing redirects (no locale prefix by design).
  if (pathname.startsWith('/api') || pathname.startsWith('/r/')) {
    // CSRF defense-in-depth: reject cross-origin mutations on the
    // cookie-authenticated routes before they reach the handler. Bearer-token
    // requests are exempt — CSRF targets ambient credentials (cookies), and
    // browsers never auto-attach an Authorization header cross-site.
    if (CSRF_MUTATING_METHODS.has(request.method) && isCsrfProtected(pathname)) {
      const hasBearer = request.headers
        .get('authorization')
        ?.toLowerCase()
        .startsWith('bearer ')
      // Cron/server-to-server calls (x-cron-secret) are not browser CSRF
      // vectors and carry no Origin — exempt them alongside bearer tokens.
      const hasCronSecret = request.headers.has('x-cron-secret')
      if (!hasBearer && !hasCronSecret && !sameOriginOk(request)) {
        return NextResponse.json({ error: 'cross-origin request blocked' }, { status: 403 })
      }
    }
    return NextResponse.next()
  }

  if (isProtectedRoute(request)) {
    const { userId } = await auth()
    if (!userId) {
      const locale = pathnameLocale(pathname) ?? routing.defaultLocale
      const signInUrl = new URL(`/${locale}/sign-in`, request.url)
      signInUrl.searchParams.set('redirect_url', request.url)
      return NextResponse.redirect(signInUrl)
    }
  }

  const hasLocalePrefix = pathnameLocale(pathname) !== undefined
  // Only a VALID cookie counts as an explicit choice — a stray/garbage value
  // must not disable detection.
  const cookieLocale = request.cookies.get('NEXT_LOCALE')?.value
  const hasLocaleCookie = routing.locales.includes(cookieLocale as Locale)

  // First visit (no cookie, no locale in the URL) → English, regardless of
  // browser language or country. A returning visitor's explicit choice
  // (cookie) always wins.
  if (!hasLocalePrefix && !hasLocaleCookie) {
    const headers = new Headers(request.headers)
    headers.set('accept-language', FIRST_VISIT_LOCALE)
    return intlMiddleware(new NextRequest(request, { headers }))
  }

  const response = intlMiddleware(request)
  if (hasLocalePrefix && isUnknownPage(pathname) && response.status === 200) {
    // Same rendering (the catch-all → localized not-found page), honest status.
    const notFound = NextResponse.rewrite(request.nextUrl, { status: 404 })
    response.headers.forEach((value, key) => {
      if (key.toLowerCase() !== 'x-middleware-rewrite') notFound.headers.set(key, value)
    })
    return notFound
  }
  return response
})

export default async function middleware(request: NextRequest, event: NextFetchEvent) {
  const rawSession = request.cookies.get(SESSION_COOKIE)?.value
  const malformed = sessionCookieMalformed(rawSession)
  const incoming = malformed ? withoutSessionCookie(request) : request

  let response: Awaited<ReturnType<NextMiddleware>>
  try {
    response = await clerkHandler(incoming, event)
  } catch (err) {
    // Last resort: if Clerk still throws while a session cookie is present,
    // clear it and reload once so the visitor is not stuck on a 500.
    if (rawSession) {
      const reload = NextResponse.redirect(request.url, 307)
      reload.cookies.delete(SESSION_COOKIE)
      return reload
    }
    throw err
  }

  if (response) {
    for (const h of CLERK_DEBUG_HEADERS) response.headers.delete(h)
    if (malformed && response instanceof NextResponse) response.cookies.delete(SESSION_COOKIE)
  }
  return response
}

export const config = {
  // Run on everything except Next internals and static files, plus all API
  // routes (Clerk needs to see them to authenticate route handlers) and
  // Clerk's auto-proxy path.
  // Dotted paths are skipped by the first pattern (static files live at the
  // root), but a dotted path UNDER a locale (/en/foo.txt, /ko/sitemap.xml) is
  // never a static file — it must still reach the 404 rewrite, so locale
  // prefixes are matched unconditionally.
  matcher: [
    '/((?!_next|_vercel|.*\\..*).*)',
    '/(ko|en)/:path*',
    '/(api|trpc)(.*)',
    '/__clerk/:path*',
  ],
}
